The ``7-base_geometry`` module
======================

Using ``BaseGeometry``
-------------------

First import
``BaseGeometry`` from the ``7-base_geometry`` module:

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Now use it:

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("my_int", 12)
    >>> bg.integer_validator("width", 89)
    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
    TypeError: name must be an integer
    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ValueError: age must be greater than 0
    >>> bg.integer_validator("distance", -4)
    Traceback (most recent call last):
    ValueError: distance must be greater than 0
    >>> bg.integer_validator("my_int")
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'
    >>> bg.integer_validator("my_int", 5.5)
    Traceback (most recent call last):
    TypeError: my_int must be an integer
    >>> bg.integer_validator("my_int", -5.5)
    Traceback (most recent call last):
    TypeError: my_int must be an integer
    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
    >>> bg.area()
    Traceback (most recent call last):
    Exception: area() is not implemented
    >>> bg.area(44)
    Traceback (most recent call last):
    TypeError: area() takes 1 positional argument but 2 were given
    >>> bg.area("hi")
    Traceback (most recent call last):
    TypeError: area() takes 1 positional argument but 2 were given

    >>> bg.integer_validator("my_int", True)
    Traceback (most recent call last):
    TypeError: my_int must be an integer
    >>> bg.integer_validator("my_int", False)
    Traceback (most recent call last):
    TypeError: my_int must be an integer

    >>> bg.integer_validator("age", (12,))
    Traceback (most recent call last):
    TypeError: age must be an integer
    >>> bg.integer_validator("age", [100])
    Traceback (most recent call last):
    TypeError: age must be an integer
    >>> bg.integer_validator("age", {3, 4})
    Traceback (most recent call last):
    TypeError: age must be an integer
    >>> bg.integer_validator("age", None)
    Traceback (most recent call last):
    TypeError: age must be an integer
